// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTC2L1JrmIPQyMF4B949WxnJu7HDUKrI8',
    appId: '1:721091898914:web:b6feca08e20607e577647b',
    messagingSenderId: '721091898914',
    projectId: 'watch-party-d4610',
    authDomain: 'watch-party-d4610.firebaseapp.com',
    storageBucket: 'watch-party-d4610.firebasestorage.app',
    measurementId: 'G-97FWQXS164',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsbZEleJgtrXzuRTzcPTfV99lJF4kqjQE',
    appId: '1:721091898914:android:ccf8a073070592a477647b',
    messagingSenderId: '721091898914',
    projectId: 'watch-party-d4610',
    storageBucket: 'watch-party-d4610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI7jMGwmvAmuG79jTeFJq0M6RvhKUq7IA',
    appId: '1:721091898914:ios:8cf95a4db1312d0377647b',
    messagingSenderId: '721091898914',
    projectId: 'watch-party-d4610',
    storageBucket: 'watch-party-d4610.firebasestorage.app',
    iosBundleId: 'com.example.watchparty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI7jMGwmvAmuG79jTeFJq0M6RvhKUq7IA',
    appId: '1:721091898914:ios:8cf95a4db1312d0377647b',
    messagingSenderId: '721091898914',
    projectId: 'watch-party-d4610',
    storageBucket: 'watch-party-d4610.firebasestorage.app',
    iosBundleId: 'com.example.watchparty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTC2L1JrmIPQyMF4B949WxnJu7HDUKrI8',
    appId: '1:721091898914:web:36b99903842adf6777647b',
    messagingSenderId: '721091898914',
    projectId: 'watch-party-d4610',
    authDomain: 'watch-party-d4610.firebaseapp.com',
    storageBucket: 'watch-party-d4610.firebasestorage.app',
    measurementId: 'G-20DFB643FN',
  );
}
